"""Read a product listing well enough to advertise it.

The packaged tool talks to Shopee's own API, which needs affiliate partner
credentials and breaks whenever that API moves. This reads Open Graph tags
instead — the metadata every shop already publishes so links preview nicely on
social media. No credentials, and it works on far more than one marketplace.

What comes back is only the raw material: a title and a product photo. The
image goes through the existing upload path to become a Flow reference, and
the advert itself is generated by the normal image pipeline.
"""
from __future__ import annotations

import html
import ipaddress
import logging
import re
import socket
from typing import Optional
from urllib.parse import urljoin, urlparse

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/affiliate", tags=["affiliate"])

# Enough for the <head> of any sane page. Product pages are megabytes of
# scripts; the tags are near the top and reading it all would be waste.
MAX_HTML_BYTES = 512 * 1024
FETCH_TIMEOUT_S = 20.0

# A real browser UA: many shops serve a stripped page (or a block) to clients
# that don't look like one, and the Open Graph tags are exactly what goes
# missing first.
_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

_META_RE = re.compile(
    r"<meta[^>]+(?:property|name)\s*=\s*[\"']([^\"']+)[\"'][^>]*>", re.I
)
_CONTENT_RE = re.compile(r"content\s*=\s*[\"']([^\"']*)[\"']", re.I)
_TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)


def _is_public_host(host: str) -> bool:
    """Same SSRF guard the image upload route applies.

    This endpoint fetches a caller-supplied URL from inside the user's
    network, so an unchecked host turns it into a probe for whatever is on
    their LAN.
    """
    if not host:
        return False
    try:
        infos = socket.getaddrinfo(host, None)
    except socket.gaierror:
        return False
    for info in infos:
        try:
            ip = ipaddress.ip_address(info[4][0])
        except ValueError:
            return False
        if (
            ip.is_loopback
            or ip.is_private
            or ip.is_link_local
            or ip.is_reserved
            or ip.is_multicast
        ):
            return False
    return True


class ProductBody(BaseModel):
    url: str = Field(min_length=1, max_length=2000)


class ProductResponse(BaseModel):
    title: Optional[str] = None
    imageUrl: Optional[str] = None
    description: Optional[str] = None
    siteName: Optional[str] = None
    price: Optional[str] = None


def _meta_map(body: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for match in _META_RE.finditer(body):
        key = match.group(1).strip().lower()
        content = _CONTENT_RE.search(match.group(0))
        if content and key not in out:
            out[key] = html.unescape(content.group(1)).strip()
    return out


@router.post("/product", response_model=ProductResponse)
async def read_product(body: ProductBody) -> ProductResponse:
    """Read a listing's title and photo.

    Shopee goes through its own product API on the user's signed-in session —
    the way the packaged tool does it — because Shopee renders the listing in
    the browser and publishes no readable tags to scrape. Everywhere else the
    Open Graph tags every shop already emits for link previews are enough, and
    need no session at all.
    """
    from flowboard.services import shopee

    url = body.url.strip()
    if "shopee." in (urlparse(url).hostname or "").lower():
        try:
            product = await shopee.fetch_product(url)
        except shopee.ShopeeError as exc:
            raise HTTPException(400, str(exc)) from None
        images = product.get("imageUrls") or []
        return ProductResponse(
            title=product.get("name") or None,
            imageUrl=images[0] if images else None,
            description=product.get("description"),
            siteName="Shopee",
            price=product.get("priceText"),
        )

    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https"):
        raise HTTPException(400, "The link must start with http:// or https://")
    if not parsed.hostname:
        raise HTTPException(400, "That link has no host.")
    if not _is_public_host(parsed.hostname):
        raise HTTPException(400, "That host is not reachable from the public internet.")

    try:
        async with httpx.AsyncClient(
            timeout=FETCH_TIMEOUT_S,
            follow_redirects=True,
            headers={"User-Agent": _UA, "Accept-Language": "vi,en;q=0.8"},
        ) as client:
            resp = await client.get(url)
    except httpx.HTTPError as exc:
        raise HTTPException(502, f"Could not open that link: {type(exc).__name__}") from exc
    if resp.status_code >= 400:
        raise HTTPException(
            502, f"That page answered {resp.status_code}."
        )

    text = resp.text[:MAX_HTML_BYTES]
    meta = _meta_map(text)

    title = meta.get("og:title") or meta.get("twitter:title")
    if not title:
        m = _TITLE_RE.search(text)
        title = html.unescape(m.group(1)).strip() if m else None

    image = meta.get("og:image") or meta.get("twitter:image")
    if image:
        # Some shops publish a protocol-relative or path-only image URL.
        image = urljoin(str(resp.url), image)

    if not title and not image:
        raise HTTPException(
            422,
            "That page published no product title or photo that could be read. "
            "Save the image yourself and use Image to Image instead.",
        )

    return ProductResponse(
        title=title,
        imageUrl=image,
        description=meta.get("og:description") or meta.get("description"),
        siteName=meta.get("og:site_name"),
        price=meta.get("product:price:amount") or meta.get("og:price:amount"),
    )
