"""Push image bytes to Flow and cache them, wherever the bytes came from.

This is the single place bytes become a Flow ``media_id``. Everything
downstream — a character node's face, a video node's start frame, a
reference image — is addressed by that id, so anything that produces an
image has to come through here or it cannot be wired into a board.

It used to live in ``routes/upload.py`` as a private function, which was
fine while the browser was the only source. It is not: ``routes/postprod``
already reached across and imported it privately (route → route), and the
worker now needs it too for images generated by OpenAI. A worker importing
a FastAPI route would drag the HTTP layer into a background process and
make ``HTTPException`` the error type of a queue job, which nothing there
can catch meaningfully.

So the transport-neutral half lives here and raises ``IngestError`` with a
suggested HTTP status; ``routes/upload`` translates that back into
``HTTPException`` for its own callers, and the worker reads ``.message``.
"""
from __future__ import annotations

import base64
import logging
from typing import Optional

from sqlmodel import select

from flowboard.db import get_session
from flowboard.db.models import Asset
from flowboard.services import media as media_service
from flowboard.services.flow_sdk import get_flow_sdk

logger = logging.getLogger(__name__)

#: Mimes accepted from any source. Flow's uploadImage takes these and the
#: local cache knows an extension for each.
ALLOWED_MIMES = {
    "image/jpeg",
    "image/png",
    "image/webp",
    "image/gif",
}

EXT_BY_MIME = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
    "image/gif": ".gif",
}


class IngestError(RuntimeError):
    """Ingest failed. ``status`` is what an HTTP caller should return.

    Carrying the status rather than raising ``HTTPException`` keeps this
    module importable from the worker, where FastAPI's exception type would
    be caught by nothing and logged as an unhandled error.
    """

    def __init__(self, message: str, *, status: int = 502, raw: object = None):
        super().__init__(message)
        self.message = message
        self.status = status
        self.raw = raw


# ── format sniffing (pure) ────────────────────────────────────────────


def sniff_mime(raw: bytes) -> Optional[str]:
    """Detect mime from magic bytes — used when the producer does not send a
    usable Content-Type, or when we want to reject a lying one."""
    if len(raw) < 12:
        return None
    if raw.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if raw.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if raw[:4] == b"RIFF" and raw[8:12] == b"WEBP":
        return "image/webp"
    if raw[:6] in (b"GIF87a", b"GIF89a"):
        return "image/gif"
    return None


def classify_aspect(width: int, height: int) -> str:
    """Classify a pixel size into Flow's IMAGE_ASPECT_RATIO_* enum so the
    frontend can default a downstream gen-dialog to match the upstream
    asset's aspect (matches what `dispatchGeneration` later persists for
    AI-generated nodes)."""
    if width <= 0 or height <= 0:
        return "IMAGE_ASPECT_RATIO_LANDSCAPE"
    ratio = width / height
    # 10% tolerance band around 1:1 → square. flowkit / Veo's enums only
    # have square / portrait / landscape — anything ratio-close maps to
    # the nearest bucket.
    if 0.91 <= ratio <= 1.1:
        return "IMAGE_ASPECT_RATIO_SQUARE"
    if ratio > 1.1:
        return "IMAGE_ASPECT_RATIO_LANDSCAPE"
    return "IMAGE_ASPECT_RATIO_PORTRAIT"


def sniff_dimensions(raw: bytes) -> Optional[tuple[int, int]]:
    """Extract (width, height) from PNG / JPEG / WebP / GIF magic-block
    headers without spinning up Pillow — same defence-in-depth philosophy
    as ``sniff_mime``. Returns None when format is unknown or the header is
    truncated."""
    if len(raw) < 24:
        return None
    # PNG: IHDR after the 8-byte sig holds width, height as big-endian u32
    if raw.startswith(b"\x89PNG\r\n\x1a\n"):
        try:
            w = int.from_bytes(raw[16:20], "big")
            h = int.from_bytes(raw[20:24], "big")
            return w, h
        except Exception:
            return None
    # GIF: 6-byte sig + 2 bytes width LE + 2 bytes height LE
    if raw[:6] in (b"GIF87a", b"GIF89a"):
        try:
            w = int.from_bytes(raw[6:8], "little")
            h = int.from_bytes(raw[8:10], "little")
            return w, h
        except Exception:
            return None
    # WebP (VP8/VP8L/VP8X) — only handle the simple lossy VP8 case fully;
    # we still extract via the VP8X chunk for the extended format.
    if raw[:4] == b"RIFF" and raw[8:12] == b"WEBP":
        chunk = raw[12:16]
        if chunk == b"VP8 " and len(raw) >= 30:
            w = int.from_bytes(raw[26:28], "little") & 0x3FFF
            h = int.from_bytes(raw[28:30], "little") & 0x3FFF
            return w, h
        if chunk == b"VP8L" and len(raw) >= 25:
            b = raw[21:25]
            w = ((b[1] & 0x3F) << 8 | b[0]) + 1
            h = ((b[3] & 0x0F) << 10 | b[2] << 2 | (b[1] & 0xC0) >> 6) + 1
            return w, h
        if chunk == b"VP8X" and len(raw) >= 30:
            w = (int.from_bytes(raw[24:27], "little") & 0xFFFFFF) + 1
            h = (int.from_bytes(raw[27:30], "little") & 0xFFFFFF) + 1
            return w, h
        return None
    # JPEG: scan for SOF0/SOF1/SOF2 marker (FFC0..FFC3 etc.)
    if raw.startswith(b"\xff\xd8\xff"):
        i = 2
        n = len(raw)
        sof_markers = {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}
        try:
            while i < n - 9:
                if raw[i] != 0xFF:
                    return None
                marker = raw[i + 1]
                # Standalone markers / restart markers — skip without length
                if marker in (0xD8, 0xD9) or 0xD0 <= marker <= 0xD7:
                    i += 2
                    continue
                # Segment with length
                seg_len = int.from_bytes(raw[i + 2 : i + 4], "big")
                if marker in sof_markers:
                    h = int.from_bytes(raw[i + 5 : i + 7], "big")
                    w = int.from_bytes(raw[i + 7 : i + 9], "big")
                    return w, h
                i += 2 + seg_len
            return None
        except Exception:
            return None
    return None


# ── the ingest itself ─────────────────────────────────────────────────


async def ingest_bytes(
    raw: bytes,
    mime: str,
    project_id: str,
    file_name: str,
    node_id: Optional[int] = None,
) -> dict:
    """Push bytes to Flow's uploadImage, cache locally, upsert Asset row.

    Returns ``{media_id, mime, size}`` plus ``width``/``height``/
    ``aspect_ratio`` when the header could be read.
    """
    image_b64 = base64.b64encode(raw).decode("ascii")
    resp = await get_flow_sdk().upload_image(
        image_base64=image_b64,
        mime_type=mime,
        project_id=project_id,
        file_name=file_name,
    )
    if resp.get("error"):
        raise IngestError(str(resp["error"]), status=502, raw=resp.get("raw"))
    media_id = resp.get("media_id")
    if not isinstance(media_id, str) or not media_service.is_valid_media_id(media_id):
        raise IngestError(
            "invalid media_id from Flow", status=502, raw=resp.get("raw")
        )
    ext = EXT_BY_MIME.get(mime, ".bin")
    cache_path = media_service.MEDIA_CACHE_DIR / f"{media_id}{ext}"
    try:
        cache_path.write_bytes(raw)
    except OSError as exc:
        logger.error("failed to write upload cache %s: %s", cache_path, exc)
        raise IngestError("failed to cache upload", status=500) from exc
    with get_session() as s:
        row = s.exec(
            select(Asset).where(Asset.uuid_media_id == media_id)
        ).first()
        if row is None:
            row = Asset(
                uuid_media_id=media_id,
                kind="image",
                local_path=str(cache_path),
                mime=mime,
                node_id=node_id,
            )
        else:
            row.local_path = str(cache_path)
            row.mime = mime
            if node_id is not None and row.node_id is None:
                row.node_id = node_id
        s.add(row)
        s.commit()
    out: dict = {"media_id": media_id, "mime": mime, "size": len(raw)}
    dims = sniff_dimensions(raw)
    if dims is not None:
        w, h = dims
        out["width"] = w
        out["height"] = h
        out["aspect_ratio"] = classify_aspect(w, h)
    return out
